# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

# command to install dependencies, e.g. pip install -r requirements.txt
install:
    - pip install Cython
    - pip install -r .travis.requirements.txt
    - pip install pep8==1.5.7
    - pip install coveralls

# command to run tests, e.g. python setup.py test
script:
    - coverage run --source=diamond test.py
    - pep8 --config=.pep8 src bin/diamond bin/diamond-setup build_doc.py setup.py test.py

after_success:
    coveralls

notifications:
  email:
    recipients:
        - kormoc@gmail.com
        - gaurav@gauravjain.org
    on_success: change
    on_failure: always
    on_start: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/89213940e8fa57ad256c
    on_success: change
    on_failure: always
    on_start: never

addons:
    apt_packages:
    - libsensors4

branches:
  only:
    - master
